# .GitHub/workflows/ci-restaurant-service.yml
name: CI - Restaurant Service

# Gatilhos: Roda em push/PR para main, mas só se houver mudanças na pasta do restaurant-service
on:
  push:
    branches: ["main"]
    paths:
      - 'restaurant-service/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'restaurant-service/**'

jobs:
  build-and-test-restaurant:
    runs-on: ubuntu-latest

    # Inicia containers do Postgres e RabbitMq para os testes de integração
    services:
      postgres:
        image: postgres:14.5
        # Variáveis de ambiente para criar o banco de dados de teste
        env:
          POSTGRES_USER: restaurantuser
          POSTGRES_PASSWORD: restaurantpass
          POSTGRES_DB: restaurantdb
        ports:
          - 5432:5432
        # Health check para garantir que o banco está pronto
        options: >-
          --health-cmd "pg_isready --username=restaurantuser --dbname=restaurantdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq:3.9-management
        env:
          RABBITMQ_DEFAULT_USER: orderSystemUser
          RABBITMQ_DEFAULT_PASS: orderSystem2925
        ports:
          - 5672:5672

    steps:
      # 1. Faz o checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2. Configura o JDK 17 com cache do Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      #3. Compila, testa e empacota o projeto com Maven
      - name: Build and Test with Maven
        # Define o diretório de trabalho para o microsserviço do restaurant
        working-directory: ./restaurant-service
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/restaurantdb
          SPRING_DATASOURCE_USERNAME: restaurantuser
          SPRING_DATASOURCE_PASSWORD: restaurantpass
          SPRING_RABBITMQ_HOST: localhost
          SPRING_RABBITMQ_PORT: 5672
          SPRING_RABBITMQ_USERNAME: orderSystemUser
          SPRING_RABBITMQ_PASSWORD: orderSystem2925
        run: mvn -B package --file pom.xml